blank_issues_enabled: false
contact_links:
  - name: ğŸ¤”ì˜ë…¼ì´ í•„ìš”í•˜ë‹¤ë©´
    url: https://connexioh-hq.slack.com/archives/C06QCRVHHLJ
    about: ê°œë°œ ì±„ë„ì—ì„œ ë¨¼ì € ì´ì•¼ê¸°ë¥¼ ë‚˜ëˆ„ì–´ ë³´ì„¸ìš”.
